### ISSUE TITLE
We should mention that it's open source & link to GitHub somewhere obvious

### ISSUE THREAD

**Issue by emk** [faradayio/cage.faraday.io#2]
This is the first or second thing a lot of people check for with a tool like this.

**Comment by erithmetic** [comment]
I always like the corner ribbons https://github.com/blog/273-github-ribbons

**Comment by emk** [comment]
Yup, that would work fine for me. We'll have some more programmer-specific detail in the main `README.md`, like the link to crates.io and the build status.

**Comment by rossmeissl** [comment]
Link: https://github.com/faradayio/cage.faraday.io/commit/8797cda2230c2140bfd7b6f040a680e16fc4282e

**Comment by rossmeissl** [comment]
Text: https://github.com/faradayio/cage.faraday.io/commit/f67ad23ea98c5be4aa3850e3e5fe632c61bc6218
